# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.dev.tikc.nl:
    container_name: orderer.dev.tikc.nl
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/dev.tikc.nl/orderers/orderer.dev.tikc.nl/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/dev.tikc.nl/orderers/orderer.dev.tikc.nl/tls/:/var/hyperledger/orderer/tls
        - orderer.dev.tikc.nl:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.dev.tikc.nl:
    container_name: peer0.dev.tikc.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dev.tikc.nl
      - CORE_PEER_ADDRESS=peer0.dev.tikc.nl:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dev.tikc.nl:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dev.tikc.nl:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dev.tikc.nl:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dev.tikc.nl/peers/peer0.dev.tikc.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dev.tikc.nl/peers/peer0.dev.tikc.nl/tls:/etc/hyperledger/fabric/tls
        - peer0.dev.tikc.nl:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.dev.tikc.nl:
    container_name: peer1.dev.tikc.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dev.tikc.nl
      - CORE_PEER_ADDRESS=peer1.dev.tikc.nl:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dev.tikc.nl:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dev.tikc.nl:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dev.tikc.nl:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dev.tikc.nl/peers/peer1.dev.tikc.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dev.tikc.nl/peers/peer1.dev.tikc.nl/tls:/etc/hyperledger/fabric/tls
        - peer1.dev.tikc.nl:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.dev.taxinnos.nl:
    container_name: peer0.dev.taxinnos.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dev.taxinnos.nl
      - CORE_PEER_ADDRESS=peer0.dev.taxinnos.nl:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dev.taxinnos.nl:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dev.taxinnos.nl:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dev.taxinnos.nl:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dev.taxinnos.nl/peers/peer0.dev.taxinnos.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dev.taxinnos.nl/peers/peer0.dev.taxinnos.nl/tls:/etc/hyperledger/fabric/tls
        - peer0.dev.taxinnos.nl:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.dev.taxinnos.nl:
    container_name: peer1.dev.taxinnos.nl
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dev.taxinnos.nl
      - CORE_PEER_ADDRESS=peer1.dev.taxinnos.nl:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dev.taxinnos.nl:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dev.taxinnos.nl:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dev.taxinnos.nl:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dev.taxinnos.nl/peers/peer1.dev.taxinnos.nl/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dev.taxinnos.nl/peers/peer1.dev.taxinnos.nl/tls:/etc/hyperledger/fabric/tls
        - peer1.dev.taxinnos.nl:/var/hyperledger/production
    ports:
      - 10051:10051
