# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dev.tikc.nl:
  peer0.dev.tikc.nl:
  peer1.dev.tikc.nl:
  peer0.dev.taxinnos.nl:
  peer1.dev.taxinnos.nl:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dev.tikc.nl-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dev.tikc.nl-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dev.tikc.nl/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dev.taxinnos.nl-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dev.taxinnos.nl-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dev.taxinnos.nl/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  orderer.dev.tikc.nl:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dev.tikc.nl
    container_name: orderer.dev.tikc.nl
    networks:
      - byfn

  peer0.dev.tikc.nl:
    container_name: peer0.dev.tikc.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dev.tikc.nl
    networks:
      - byfn

  peer1.dev.tikc.nl:
    container_name: peer1.dev.tikc.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.dev.tikc.nl
    networks:
      - byfn

  peer0.dev.taxinnos.nl:
    container_name: peer0.dev.taxinnos.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dev.taxinnos.nl
    networks:
      - byfn

  peer1.dev.taxinnos.nl:
    container_name: peer1.dev.taxinnos.nl
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.dev.taxinnos.nl
    networks:
      - byfn
